/**
 * Seed data for 15 BusVT (Vehículos Tipo)
 * TRANSPORTES VILCABAMBATURIS CÍA. LTDA.
 * Todas las frecuencias son Loja ↔ Vilcabamba
 */

export interface VTFrecuencia {
  routeFrom: string;
  routeTo: string;
  time: string;
}

export interface VTData {
  codigo: string;
  nombre: string;
  frecuencias: VTFrecuencia[];
}

export const VT_DATA: VTData[] = [
  {
    codigo: 'VT1',
    nombre: 'VT1 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '18:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '19:00' },
    ],
  },
  {
    codigo: 'VT2',
    nombre: 'VT2 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '12:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '13:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '13:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '14:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '15:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '16:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
  {
    codigo: 'VT3',
    nombre: 'VT3 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
  {
    codigo: 'VT4',
    nombre: 'VT4 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
    ],
  },
  {
    codigo: 'VT5',
    nombre: 'VT5 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '18:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '19:00' },
    ],
  },
  {
    codigo: 'VT6',
    nombre: 'VT6 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '12:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '13:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
    ],
  },
  {
    codigo: 'VT7',
    nombre: 'VT7 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '12:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '13:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:30' },
    ],
  },
  {
    codigo: 'VT8',
    nombre: 'VT8 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '13:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '14:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:30' },
    ],
  },
  {
    codigo: 'VT9',
    nombre: 'VT9 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
    ],
  },
  {
    codigo: 'VT10',
    nombre: 'VT10 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '15:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '16:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
  {
    codigo: 'VT11',
    nombre: 'VT11 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
    ],
  },
  {
    codigo: 'VT12',
    nombre: 'VT12 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '12:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '13:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '18:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '19:00' },
    ],
  },
  {
    codigo: 'VT13',
    nombre: 'VT13 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '15:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '16:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
  {
    codigo: 'VT14',
    nombre: 'VT14 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '06:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '07:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '08:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '09:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '10:30' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '11:30' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '14:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '15:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '16:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '17:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
  {
    codigo: 'VT15',
    nombre: 'VT15 - Loja Vilcabamba',
    frecuencias: [
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '05:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '06:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '07:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '08:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '09:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '10:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '11:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '12:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '13:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '14:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '15:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '16:00' },
      { routeFrom: 'Loja', routeTo: 'Vilcabamba', time: '17:00' },
      { routeFrom: 'Vilcabamba', routeTo: 'Loja', time: '18:00' },
    ],
  },
];
